[bot]
    token="TOKEN"  # replace it with your bot token

[redis]
    host="127.0.0.1"  # localhost
    port=6379  # Redis port is 6379 by default
    db=0

[discord]
    newbie_role_id=951823783835078708
    guild_id=951816293592469514
    verify_channel_id=951823726905819158

[message]
    verify_button="Verify"
