[bot]
    token="Your Bot Token Here"

[redis]
    host="localhost"
    port=6379
    db=0

[discord]
    newbie_role_id=951823783835078708
    guild_id=951816293592469514
    verify_channel_id=951823726905819158

[message]
    verify_button="Verify"